version:  '3'
services:
#  sonarqube:
#    image: sonarqube:8-community
#    networks:
#      - app-network
#    ports:
#      - '9000:9000'
#    environment:
#      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  db:
    build:
      context: docker
      dockerfile: Dockerfile.mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  c16:
    build:
      context: c16
      dockerfile: Dockerfile.c16
    restart: always
    ports:
      - '9090:9090'
    expose:
      - '9090'
    depends_on:
      - 'db'
    volumes:
      - my-db:/var/lib/mysql
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - 'c16'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

